### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by marcondesmacaneiro** [alleveenstra/Mujina#3]
I like to test de Mujina project

My IdP ok, but my SP not ok! 

I not understand how it works

I try this URL: http://localhost:8080/SingleSignOnService/vo:teste

and return this page

---

HTTP ERROR 404

Problem accessing /SingleSignOnService/vo:test. Reason:

```
NOT_FOUND
```

Powered by Jetty://

---

What is -> vo:test?

I need configure this parameter?

thanks

**Comment by alleveenstra** [comment]
Great to see you are using Mujina! Do you run the project using maven's jetty:run? If so, the SP is available on port 9090. Try and have a look on http://localhost:9090/ .

Hopefully this helps and if you have any more questions feel free to contact me.

**Comment by marcondesmacaneiro** [comment]
OK, i try to acess this URL, localhost:9090, but my browser is redirect automatically to http://localhost:8080/SingleSignOnService/vo:teste

Sorry, but I'ma junior in this tecnology

**Comment by alleveenstra** [comment]
Can you give me more information on what you did and what you want to accomplish? For what do you want to use Mujina?

I'm guessing you changed the ssoServiceURL parameter using the REST service. Now the SP will redirect to a location that is not available on the Mujina IdP.

**Comment by marcondesmacaneiro** [comment]
I am studying for a SAML attribute aggregation strategies for the Brazilian government.
In a master's project.

But not quite understand how funcionas techniques SSO.

I made some modifications using the REST API, but without knowing he was doing.

The IdP ok, but the SP redirects to URL above informed.
But it seems that the redirect URL does not exist.

Should I perform a reset in the settings?

**Comment by alleveenstra** [comment]
You can use Mujina to test SAML applications. For example, if you want to try out Shibboleth (a well known IdP) you can easily setup Mujina's SP to use it:

curl -v -H "Accept: application/json" \
        -H "Content-type: application/json" \
        -X PUT -d '{"value": "http://platform.government.br/shibboleth/sso"}' \
        http://localhost:9090/api/ssoServiceURL

You can reset the SP using:

curl -v -H "Accept: application/json" \
        -H "Content-type: application/json" \
        -X POST \
        http://localhost:9090/api/reset

**Comment by marcondesmacaneiro** [comment]
right, then create even need an IdP (Shibboleth) localmetne for that.

I could use the Mujina to create an active client to aggregate attributes from multiple IdPs?

**Comment by alleveenstra** [comment]
No, you can not do that with Mujina.

I don't know any project that does exactly what you want. The OpenConext (https://github.com/OpenConext) project comes close. OpenConext is a proxy between IdP's and SP's. They also augment and filter SAML assertions, which is close to what you want to do.

**Comment by marcondesmacaneiro** [comment]
I understand, but I will still use the Mujina to study and learn.

My proposal is to create a local proxy, using JavaWebStart.
To perform the aggregation of attributes and send the assertions service providers.

Thanks for the help!

**Comment by alleveenstra** [comment]
You're welcome. Feel free to ask me questions regarding the code.
